### ISSUE TITLE
Windows: Imperfect operation

### ISSUE THREAD

**Issue by ekfacile** [vlang/vls#495]
As far as I can tell, VLS no longer works correctly on Windows in V version 0.5.1 and later.

When the extension is launched, you will typically see two popups. These enable code highlighting (immediately) and popup functionality **(after any changes have been made to the code)**.

- V Language Server is starting.
- V Language Server is now active.

It worked fine up to version 0.5.0, but in version 0.5.1, the popup function sometimes works and sometimes doesn’t.

In commit `5dd162f`, only the following single popup appears, and only code highlighting works. The popup function does not work at all.

- V Language Server is starting.

**Comment by ekfacile** [comment]
Commit c3f66bc: Still imperfect operation.

You’ll see a ton of warnings as soon as you run `npm install`, but even after running `npm update`, three critical vulnerabilities remain unaddressed.

**Comment by martinkeefe** [comment]
I can't even compile VLS. When I run `v .` I get:

```
handlers.v:468:24: error: unexpected `or` block, the field `range` is not an Option or a Result
```

`v --version` gives:
```
V 0.5.1 0c3183c
```

**Comment by JalonSolov** [comment]
With latest `V 0.5.1 9f57c74` it compiles clean on Linux.

There is a lot of "churn" in V right now.  If you hit a problem, `v up` and try again.
