### ISSUE TITLE
vls does not compile with v master (0.2.2 9d4783a)

### ISSUE THREAD

**Issue by leighmcculloch** [vlang/vls#117]
It appears that vls does not compile with the current v master (0.2.2 9d4783a).

```
.../vls/cmd/vls/stdio.v:11:8: error: cannot register struct `Stdio`, another type with this name exists
    9 | fn C.fgetc(stream byteptr) int
   10 | 
   11 | struct Stdio {
      |        ~~~~~
   12 | pub mut:
   13 |     debug bool
```

**Comment by leighmcculloch** [comment]
As far as I can see there is only one definition of the type `Stdio` in vls at:
https://github.com/vlang/vls/blob/6a5e814893c7bd7b94d2f4c3bff377c68b9324b4/cmd/vls/stdio.v#L11-L14

Could this be an error in the compiler?

**Comment by nedpals** [comment]
@leighmcculloch most probably. How did you compile VLS?

**Comment by leighmcculloch** [comment]
This is my install script for vls: https://github.com/leighmcculloch/dotfiles/blob/989f2bc1a0ff24515a935e58db699c056164e775/files/lazybin/vls

I'm doing this:

```sh
git clone https://github.com/vlang/vls $LOCAL/vls
v -prod $LOCAL/vls/cmd/vls
```

Note that this same behavior happens if I run like so:
```
cd $LOCAL/vls
v .
```

**Comment by nedpals** [comment]
@leighmcculloch Do you have `vls` also installed on `.vmodules`? I cannot reproduce the error you mentioned on a non-vmodules dir setup

**Comment by nedpals** [comment]
Regardless, this issue should be raised into the [vlang/v](https://github.com/vlang/v/issues) repo.

**Comment by leighmcculloch** [comment]
@nedpals could you transfer the issue to the [vlang/v](https://github.com/vlang/v/issues) repo?

---

Here is a `Dockerfile` that reproduces the problem.

```Dockerfile
FROM ubuntu:20.04

RUN apt update
RUN apt install -y git make gcc

RUN git clone https://github.com/vlang/v
RUN git -C /v checkout 99a2fd76c81bc8da4604ecca9eadb997bdfa4b25
RUN make -C /v

RUN git clone https://github.com/vlang/vls
RUN git -C /vls checkout 5d21339b10c4619036e482c03670e4b52d02ce59
RUN /v/v -prod /vls/cmd/vls
```

The commits checked out are the v (vlang/v@99a2fd76c81bc8da4604ecca9eadb997bdfa4b25) and vls (vlang/vls@5d21339b10c4619036e482c03670e4b52d02ce59) masters at this moment.

You can build and run the Dockerfile with the following commands:
```sh
docker build -t vls117 .
docker run --rm -it vls117
```

The last step, step 9, errors with the following error:
```
 > [9/9] RUN /v/v -prod /vls/cmd/vls:
#12 0.459 /vls/cmd/vls/stdio.v:11:8: error: cannot register struct `Stdio`, another type with this name exists
#12 0.459     9 | fn C.fgetc(stream byteptr) int
#12 0.459    10 |
#12 0.459    11 | struct Stdio {
#12 0.459       |        ~~~~~
#12 0.459    12 | pub mut:
#12 0.459    13 |     debug bool
```

**Comment by nedpals** [comment]
I'll transfer it now, thanks for the info
